### ISSUE TITLE
License for the code in colors.h

### ISSUE THREAD

**Issue by leehambley** [gon1332/fort320#1]
Gi @gon1332 I realize this might seem silly when the header is only a handful of lines long, and contains nothing (really) clever., I'd love to use it in my project, but without a licence, I can't! 

Could you clarify the terms under which `fort320`'s code is available, please?

**Comment by leehambley** [comment]
I've implemented it myself in terms of `const` strings in a namespace of my logger, so I guess there's no possible conflict :)

**Comment by gon1332** [comment]
I am glad you finally found a solution. However, there is no problem using it as is. :)

**Comment by leehambley** [comment]
Thanks @gon1332
